### ISSUE TITLE
Inclusion of Mod 1?

### ISSUE THREAD

**Issue by Peterstigers** [ereb-thanatos/cossacks-revamp-2017#13]
Hi,

I installed Cossacks Back to War 1.42, and it works great on Windows 10. The only problem I have with it so far is that it doesn't seem to include the contents of Mod 1.

[http://cossacks.heavengames.com/mod/#4](url)

I noticed the added cannons were missing specifically. Is there a way to add the contents of Mod 1 to your patch. I tried to install Mod 1 of the CD on top of the 1.42 files, and the game won't startup.

**Comment by ereb-thanatos** [comment]
Hello,
thank you for showing interest in modding the Cossacks 1.42 build. I do not expect that any of the existing mods will work out of the box, because the 1.42 build accesses its resources through the non-standard _resources.gsc_ archive. You could try to overwrite the relevant resources manually, though. Please let me know if you succeed in doing so.

**Comment by ereb-thanatos** [comment]
Closing due to lack of a response.

**Comment by MisterCoderman** [comment]
Hello
The mod is included in version 1.52.
https://github.com/MisterCoderman/cossacks-2025
