### ISSUE TITLE
Game Speed

### ISSUE THREAD

**Issue by Zamparelli** [ereb-thanatos/cossacks-revamp-2017#16]
Thanks for this mod, it is excellent! I have a question: Even on slow mode the game speed is still a little too fast, is there a file where I can manually set the speed? The game speed slider does not appear on my menu (which I assume is intentional).

**Comment by ereb-thanatos** [comment]
Hello Zamparelli,
I am glad that you enjoy playing my build of this classic RTS. As you have already noticed, I have constrained the speed adjustment functionality. This was done because there were quite a few bugs related to the game speed setting and to runtime changes to this setting. I am afraid that you only can choose between the provided alternatives. The speed settings were also picked with the experienced / competitive Cossacks player community in mind. Those folks tend to play at higher speeds : )
I hope that you will enjoy the game nevertheless.
Best regards,
Ereb
