### ISSUE TITLE
Mods not working

### ISSUE THREAD

**Issue by micki9393** [ereb-thanatos/cossacks-revamp-2017#8]
Wow I didn't know of the existence of this fantastic project, my problem is simple I have a mod .gs1 that doesn't work with this version of the game, how come? However I was wondering have you ever thought of trying to make this project similar to the mod imperia but what works for multiplayer? Or to insert something similar to a dynamic diplomacy with dynamic alliances, merchants, to be able to transfer resources also to AI, or the inclusion of morale as in cossacks 2?

**Comment by ereb-thanatos** [comment]
> I have a mod .gs1 that doesn't work with this version of the game, how come?

I altered the resource file lookup. If you want to apply a mod on top of the provided *resources.gsc*, you have to name it *override.gsc*. For details see [Main executable/Arc/GSCset.cpp:290](https://github.com/ereb-thanatos/cossacks-revamp-2017/blob/master/src/Main%20executable/Arc/GSCset.cpp#L290).
> have you ever thought of [...]

This initially was a small project of mine because I wanted to play the old game on a modern system. I have no further plans for it.

**Comment by puffdelore** [comment]
> I altered the resource file lookup. If you want to apply a mod on top of the provided _resources.gsc_, you have to name it _override.gsc_. For details see [Main executable/Arc/GSCset.cpp:290](https://github.com/ereb-thanatos/cossacks-revamp-2017/blob/master/src/Main%20executable/Arc/GSCset.cpp#L290).

Hi, how would I go about applying a mod that has mods01.gs1 and mods02.gs1? I have tried combining those two files into one override.gsc, but it is an imperfect solution. Is there any way around this? Awesome work, by the way!
